# Generated by Django 3.1 on 2022-05-22 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='counter_target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plastic_bag_target', models.PositiveIntegerField(default=0)),
                ('plastic_bottle_target', models.PositiveIntegerField(default=0)),
                ('plastic_wrapper_target', models.PositiveIntegerField(default=0)),
                ('plastic_cup_straw_target', models.PositiveIntegerField(default=0)),
                ('paper_tissue_target', models.PositiveIntegerField(default=0)),
                ('paper_target', models.PositiveIntegerField(default=0)),
                ('paper_cup_target', models.PositiveIntegerField(default=0)),
                ('paper_cigarette_butt_target', models.PositiveIntegerField(default=0)),
                ('misc_glass_bottle_target', models.PositiveIntegerField(default=0)),
                ('misc_mask_target', models.PositiveIntegerField(default=0)),
                ('misc_others_target', models.PositiveIntegerField(default=0)),
                ('misc_can_target', models.PositiveIntegerField(default=0)),
                ('date_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='deeds1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deed', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=80)),
                ('date_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='deeds2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deed', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=80)),
                ('date_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='deeds3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deed', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=80)),
                ('date_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='globalLamrim2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deed', models.CharField(max_length=600)),
                ('name', models.CharField(max_length=80)),
                ('date_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='plastic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plastic_bag_counter', models.PositiveIntegerField(default=0)),
                ('plastic_bottle_counter', models.PositiveIntegerField(default=0)),
                ('plastic_wrapper_counter', models.PositiveIntegerField(default=0)),
                ('plastic_cup_straw_counter', models.PositiveIntegerField(default=0)),
                ('plastic_bag_target', models.PositiveIntegerField(default=0)),
                ('plastic_bottle_target', models.PositiveIntegerField(default=0)),
                ('plastic_wrapper_target', models.PositiveIntegerField(default=0)),
                ('plastic_cup_straw_target', models.PositiveIntegerField(default=0)),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_tissue_counter', models.PositiveIntegerField(default=0)),
                ('paper_counter', models.PositiveIntegerField(default=0)),
                ('paper_cup_counter', models.PositiveIntegerField(default=0)),
                ('paper_cigarette_butt_counter', models.PositiveIntegerField(default=0)),
                ('paper_tissue_target', models.PositiveIntegerField(default=0)),
                ('paper_target', models.PositiveIntegerField(default=0)),
                ('paper_cup_target', models.PositiveIntegerField(default=0)),
                ('paper_cigarette_butt_target', models.PositiveIntegerField(default=0)),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='misc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('misc_glass_bottle_counter', models.PositiveIntegerField(default=0)),
                ('misc_mask_counter', models.PositiveIntegerField(default=0)),
                ('misc_others_counter', models.PositiveIntegerField(default=0)),
                ('misc_can_counter', models.PositiveIntegerField(default=0)),
                ('misc_glass_bottle_target', models.PositiveIntegerField(default=0)),
                ('misc_mask_target', models.PositiveIntegerField(default=0)),
                ('misc_others_target', models.PositiveIntegerField(default=0)),
                ('misc_can_target', models.PositiveIntegerField(default=0)),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
